### ISSUE TITLE
reverse type if the interval limits are swapped

### ISSUE THREAD

**Issue by mgacc0** [psolymos/intrval#12]
When an interval is expressed in reverse order,
it would be coherent to swap the order of parentheses and brackets:
```{r}
expect_false(.intrval(4, c(5, 4), "[)"))
# Error: .intrval(4, c(5, 4), "[)") isn't false.

expect_false(.intrval(4, c(4, 5), "(]"))

expect_true(.intrval(5, c(5, 4), "[)"))
# Error: .intrval(5, c(5, 4), "[)") isn't true.
```

---
```{r}
reverse_type <- function (type) {
  ifelse(type=="(]", "[)",
         ifelse(type=="[)", "(]", type))
}
reverse_type("(]")
# [1] "[)"
reverse_type("[)")
# [1] "(]"
```

---
Or maybe a warning should be shown when a swapped interval is found?

**Comment by psolymos** [comment]
That is so by design explained in this [blog post](http://peter.solymos.org/code/2016/12/02/relational-operators-for-intervals-with-the-intrval-r-package.html) among the motivation. The interval operator expresses the type of lower (left bracket) and upper (right bracket) endpoint, while in the RHS the values are sorted, so that smaller becomes the lower endpoint irrespective of sorting.
